### ISSUE TITLE
About Nick Sacrifice

### ISSUE THREAD

**Issue by jjjaldon** [wordush/korobeiniki#1]
Hello good afternoon, I do not know how to say this in an educated way, but I have been using my Nick Sacrifice for my repositories for many years where I host my work and I see that you have it and I cannot use it for this reason. **The question is:** Would it be very damaging for you to choose another nick (`! = || <> Sacrifice`, depending on the language you use...) other than Sacrifice so that I can legitimately use it?. I would greatly appreciate it.

To have a reference, I show you an example where you can check that not only since 2016, but before 2009 at least I use that nickname. [Sacrifice in gitlab](https://gitlab.com/Sacrifice)

**Comment by wordush** [comment]
It's okay. I was change nickname. 

Viele Grusse, Auf Wiedersehen :)

**Comment by jjjaldon** [comment]
You don't know how I thank you. Thank you.
Sie wissen nicht, wie ich Ihnen danke. Vielen Dank
